from backend.public_backend import *

header_line_1 = "Anthony's Home Appliance Repair Shop"
header_line_2 = "#305 Maharlika Highway, La Torre,"
header_line_3 = "Talavera, Nueva Ecija 3114"
header_line_4 = "Contact #: 09083287926 / 09368505809"
header_line_5 = 'PROOF OF PURCHASED'

dash_line_style = "border: none; border-bottom: 1px dashed black;"

footer = 'This receipt is generated by the tsystem.\
tsystem is an\nopen-source software developed by Gerald Dave Trajano\n\
For more information, please visit ---\nhttps://github.com/geraldtgit/aharts\nEmail: geralddavetrajano@gmail.com'

# Broken Line
#dash_line_style = "border: none; border-bottom: 1px dashed black;"
#layout.addWidget(QFrame(self, frameShape=QFrame.HLine, frameShadow=QFrame.Sunken, lineWidth=1, styleSheet=dash_line_style))


process_dttm = datetime.datetime.now().strftime("%Y-%m-%d_%H.%M.%S")

# log file path + new file name
receipt_absolute_dir = receipt_db_dir + "receipt_" + process_dttm + ".txt"

def check_receipt_db():
    # Check if the directory exists, and create it if necessary
    if not os.path.exists(receipt_db_dir):
        os.makedirs(receipt_db_dir)


# Open the file in append mode and write the log message
'''
def log_message(message):
    check_receipt_db()
    with open(receipt_absolute_dir, 'a') as file:
        file.write(f"{process_dttm} : {message}" + "\n")
'''
